apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql-rs
  labels:
    app: task-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-rs
  template:
    metadata:
      labels:
        app: task-rs
    spec:
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql
        image: mysql
        env:
          # Test, use secret in prod
        - name: MYSQL_ROOT_PASSWORD
          value: MyV3ryS3curePa55
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-rs
          mountPath: /var/lib/mysql
